# Generated by Django 5.2.4 on 2025-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
