# Generated by Django 5.2.4 on 2025-07-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.RunSQL(
            sql="INSERT INTO store_collection (title) VALUES ('collection1')",
            reverse_sql="DELETE FROM store_collection WHERE title='collection1'",
        )
    ]
