# Generated by Django 5.2.5 on 2025-08-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
