# Generated by Django 5.2.5 on 2025-08-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_productimage_image"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM store_collection WHERE title='collection1'",
            reverse_sql=migrations.RunSQL.noop,
            # This explicitly states that the operation has no reverse.
        )
    ]
