# Generated by Django 5.2.6 on 2025-09-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_reverse_demo_migration_005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
