# Generated by Django 5.2.6 on 2026-07-07 07:19
# (then edited to add the `Customer` backfill)

from django.conf import settings
from django.db import migrations, models


def backfill_customers(apps, schema_editor):
    """Create the missing `Customer` rows for users created before the
    `create_customer_for_new_user` post_save signal existed."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Customer = apps.get_model("store", "Customer")
    Customer.objects.bulk_create(
        Customer(user_id=user.id)
        for user in User.objects.filter(customer__isnull=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cartitem_options_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_customers, migrations.RunPython.noop),
    ]
